name: Playwright Test Automation on MacOS

on:
  push:
    branches:
      - main  # Change branch if needed
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest  # Change to macOS runner as you mentioned using macOS

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Pulls your repo code

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Install Node.js

      - name: Install Dependencies
        run: npm install  # Install Playwright and project dependencies

      - name: Install Playwright Browsers
        run: npx playwright install  # Ensure browsers are installed

      - name: Run Playwright Tests
        run: npx playwright test --reporter=html  # Run tests & generate report

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v2  # Save the report as an artifact (use v2 for stability)
        with:
          name: playwright-report
          path: playwright-reports/  # Path to your report directory
